name : shell commands
on: [push]           #on: push or [push,...] can be an event on array of event
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run : | # running multiline commands
          node -v
          npm -v 